/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "alfama": {
    "base": "alfama",
    "width": 1920,
    "height": 1080,
    "fallbackWidth": 800,
    "fallbackHeight": 450,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "belem": {
    "base": "belem",
    "width": 1920,
    "height": 1832,
    "fallbackWidth": 1920,
    "fallbackHeight": 1832,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cascais": {
    "base": "cascais",
    "width": 1024,
    "height": 768,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coast": {
    "base": "coast",
    "width": 1224,
    "height": 1632,
    "fallbackWidth": 1224,
    "fallbackHeight": 1632,
    "widths": [
      320,
      480,
      640,
      800,
      960
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "compare": {
    "base": "compare",
    "width": 1920,
    "height": 1310,
    "fallbackWidth": 1920,
    "fallbackHeight": 1310,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 1920,
    "height": 904,
    "fallbackWidth": 1920,
    "fallbackHeight": 904,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "family": {
    "base": "family",
    "width": 1024,
    "height": 768,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food": {
    "base": "food",
    "width": 1280,
    "height": 847,
    "fallbackWidth": 800,
    "fallbackHeight": 529,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 1349,
    "height": 900,
    "fallbackWidth": 1349,
    "fallbackHeight": 900,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "historic": {
    "base": "historic",
    "width": 1920,
    "height": 2899,
    "fallbackWidth": 800,
    "fallbackHeight": 1208,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "miradouro": {
    "base": "miradouro",
    "width": 1920,
    "height": 415,
    "fallbackWidth": 800,
    "fallbackHeight": 173,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 1920,
    "height": 1832,
    "fallbackWidth": 1920,
    "fallbackHeight": 1832,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "pasteis": {
    "base": "pasteis",
    "width": 1280,
    "height": 847,
    "fallbackWidth": 800,
    "fallbackHeight": 529,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "photography": {
    "base": "photography",
    "width": 1920,
    "height": 1440,
    "fallbackWidth": 1920,
    "fallbackHeight": 1440,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "private": {
    "base": "private",
    "width": 1224,
    "height": 1632,
    "fallbackWidth": 800,
    "fallbackHeight": 1067,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "sintra": {
    "base": "sintra",
    "width": 1920,
    "height": 1310,
    "fallbackWidth": 1920,
    "fallbackHeight": 1310,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "tram": {
    "base": "tram",
    "width": 1834,
    "height": 1832,
    "fallbackWidth": 1834,
    "fallbackHeight": 1832,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "walking": {
    "base": "walking",
    "width": 1920,
    "height": 1143,
    "fallbackWidth": 800,
    "fallbackHeight": 476,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "wine": {
    "base": "wine",
    "width": 1920,
    "height": 1920,
    "fallbackWidth": 800,
    "fallbackHeight": 800,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
